# Generated by Django 4.1.7 on 2023-06-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAluno', models.IntegerField()),
                ('codigoProfessor', models.IntegerField()),
                ('codigoTurma', models.IntegerField()),
            ],
        ),
    ]
